blank_issues_enabled: false

contact_links:
  - name: ğŸ¤” Question
    url: https://github.com/lihbr/lihbr-apex/discussions
    about: Ask a question about the package. You will usually get support there more quickly!
  - name: ğŸ¦‹ Lucie's Bluesky
    url: https://bsky.app/profile/lihbr.com
    about: Get in touch with me about this package, or anything else on Bluesky
  - name: ğŸ˜ Lucie's Mastodon
    url: https://mastodon.social/@lihbr
    about: Get in touch with me about this package, or anything else on Mastodon
